### ISSUE TITLE
failure getting reach build past loading screen [Reach] branch

### ISSUE THREAD

**Issue by eric-schleicher** [pboyer/flood#131]
Hi there, I'm trying to bring the reach branch up on a virtual server.  I followed the instructions from the main readme and it appeared to install correctly.

I launched the app and connected to it. but asked to 'wait for it'... forever
![image](https://cloud.githubusercontent.com/assets/8261783/6035967/2646d1f6-abf2-11e4-8ca0-6597924c5f69.png)

i tried in firefox as well same result.  opening the console show that socket connection can't be opened...
![image](https://cloud.githubusercontent.com/assets/8261783/6035989/5523865e-abf2-11e4-965f-20a946fa48f4.png)

previously, i was able to bring the master branch up, got into the editor, but couldn't product any geometry.

Super interested in getting this running and learning more.  please let me know if there is something simple i'im missing

**Comment by eric-schleicher** [comment]
Hi there, in looking through both the reach and master branch code it look like i need to be running dynamo locally?  I dynamo a requirement to run flood?

**Comment by pboyer** [comment]
Hi @eric-schleicher,

Sorry for the slowness!

I can't support the Reach branch for external dev's at this point.  The master branch should be fine for CSG.js based geometry and should work as described in the README.
